[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
authors = [
    { name = "JJMC89" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Wiki",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = [
    "pywikibot >= 11.2.0",
]
description = "Extends the Pywikibot library"
keywords = [ "bot", "mediawiki" ]
license = "MIT"
name = "pywikibot-extensions"
readme = "README.md"
requires-python = ">=3.10"
version = "26.4.9"

[project.urls]
source = "https://github.com/JJMC89/pywikibot-extensions"


[tool.black]
target-version = ["py310"]
line-length = 79  # default: 88


[tool.coverage]

[tool.coverage.run]
plugins = [
    "covdefaults",
]


[tool.isort]
atomic = true
profile = "black"
py_version = 310


[tool.mypy]
python_version = "3.10"
enable_error_code = [
    "ignore-without-code",
]
strict = true
disallow_subclassing_any = false

[[tool.mypy.overrides]]
module = "pywikibot.*"
ignore_missing_imports = true


[tool.poetry]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.test.dependencies]
covdefaults = "2.3.0"
pytest = "9.0.3"
pytest-cov = "7.1.0"
pytest-mock = "3.15.1"
pytest-randomly = "4.1.0"
pytest-socket = "0.7.0"


[tool.pytest]
addopts = [
    "--cov",
    "--no-cov-on-fail",
]
strict = true
