name: Draft release
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yaml
