name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    permissions:
      security-events: write
  build-publish:
    name: Build and publish release
    needs: ci
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          persist-credentials: false
      - name: Check version and git tag
        run: |
          DATE=v$(date -u +%y.%-m.%-d)
          VERSION=v$(poetry version --short)
          TAG=$(git describe --tags --abbrev=0)
          if [ $VERSION != $DATE ]; then
            echo Version should be $DATE instead of $VERSION.
            exit 1
          elif [ $TAG != $DATE ]; then
            echo Tag should be $DATE instead of $TAG.
            exit 1
          fi
      - name: Build
        run: poetry build
      - name: GitHub release with assets
        id: release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: dist/*
          generate_release_notes: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          user: __token__
      - name: Rollback release on failure
        if: failure() && steps.release.outputs.id != ''
        uses: author/action-rollback@1.0.3
        with:
          release_id: ${{ steps.release.outputs.id }}
