name: Publish
on:
  release:
    types:
      - released
jobs:
  build-publish:
    name: Build and publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
      - name: Build
        run: poetry build
      - name: Upload to GitHub release
        uses: shogo82148/actions-upload-release-asset@v1.5.0
        with:
          asset_path: dist/*
          upload_url: ${{ github.event.release.upload_url }}
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          user: __token__
