name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  build:
    name: build distribution
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: check version and git tag
        run: |
          DATE=v$(date -u +%y.%-m.%-d)
          VERSION=v$(poetry version --short)
          TAG=$(git describe --tags --abbrev=0)
          if [ $VERSION != $DATE ]; then
            echo version should be $DATE instead of $VERSION.
            exit 1
          elif [ $TAG != $DATE ]; then
            echo tag should be $DATE instead of $TAG.
            exit 1
          fi
      - name: build
        run: poetry build
      - name: upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  publish:
    environment: publish
    name: publish distribution
    needs: build
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: github release with assets
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: rollback release on failure
        if: failure() && steps.release.outputs.id != ''
        uses: author/action-rollback@1.0.3
        with:
          release_id: ${{ steps.release.outputs.id }}
